# Generated by Django 3.2.7 on 2026-02-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_malpraticedetection_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpraticedetection',
            name='probability_score',
            field=models.FloatField(blank=True, help_text='AI-computed probability of malpractice (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehall',
            name='building',
            field=models.CharField(choices=[('MAIN', 'Main Block'), ('KE', 'Second Block'), ('PG', 'Third Block')], max_length=50),
        ),
    ]
