# Generated by Django 6.0.2 on 2026-02-25 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20260225_0107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='malpraticedetection',
            name='source_type',
            field=models.CharField(choices=[('live', 'Live Camera'), ('recorded', 'Recorded Video')], default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='malpraticedetection',
            name='teacher_visible',
            field=models.BooleanField(default=False, help_text='Visible to teacher only after admin review'),
        ),
        migrations.AddField(
            model_name='malpraticedetection',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CameraSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested by Admin'), ('active', 'Camera Active'), ('stopped', 'Camera Stopped'), ('denied', 'Denied by Teacher')], default='requested', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lecturehall')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('live', 'Live Camera'), ('recorded', 'Recorded Video')], default='live', max_length=10)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('session_start_time', models.TimeField(blank=True, null=True)),
                ('session_end_time', models.TimeField(blank=True, null=True)),
                ('logs_reviewed', models.IntegerField(default=0)),
                ('logs_flagged', models.IntegerField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
                ('lecture_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lecturehall')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
