# Generated by Django 6.0.2 on 2026-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_teacherprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested by Admin'), ('active', 'Camera Active'), ('stopped', 'Camera Stopped'), ('denied', 'Denied by Teacher')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='malpraticedetection',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='malpraticedetection',
            name='probability_score',
            field=models.FloatField(blank=True, db_index=True, help_text='AI-computed probability of malpractice (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='malpraticedetection',
            name='source_type',
            field=models.CharField(choices=[('live', 'Live Camera'), ('recorded', 'Recorded Video')], db_index=True, default='live', max_length=10),
        ),
        migrations.AlterField(
            model_name='malpraticedetection',
            name='teacher_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible to teacher only after admin review'),
        ),
        migrations.AlterField(
            model_name='malpraticedetection',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
